# Generated by Django 3.1.3 on 2021-01-01 08:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20210101_1203'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='comment_date',
            new_name='timestamp',
        ),
    ]
